from os import remove, rename, environ
from os.path import exists, getmtime
from shutil import copyfile
from subprocess import run, PIPE, Popen
from re import search, findall
from time import time
import struct
import numpy as np

from mddb_workflow.utils.auxiliar import load_json, ToolError, warn, get_auxiliar_filepath
from mddb_workflow.utils.constants import GROMACS_EXECUTABLE, GREY_HEADER, COLOR_END, GLOBALS
from mddb_workflow.utils.constants import GROMACS_MASSES_FILENAME
from mddb_workflow.utils.file import File
from mddb_workflow.utils.type_hints import *
from mddb_workflow.tools.fix_gromacs_masses import fix_gromacs_masses

# Set some constants
GROMACS_SUPPORTED_TRAJECTORY_FORMATS = { 'xtc', 'trr' }
GROMACS_SUPPORTED_STRUCTURE_FORMATS = { 'gro', 'pdb' }
GROMACS_SUPPORTED_INPUT_TOPOLOGY_FORMATS = { 'tpr', *GROMACS_SUPPORTED_STRUCTURE_FORMATS }

GROMACS_MASSES_ERROR = r'Can not find mass in database for atom ([a-zA-Z0-9]*)'

def run_gromacs(
    command : str,
    user_input : Optional[str] = None,
    expected_output_filepath : Optional[str] = 'auto',
    show_output_logs : bool = False,
    show_error_logs : bool = False) -> tuple[str, str]:
    """ Set a function to call gromacs in a more confortable and standarized way:
    - Standard gromacs executable, which may be provided by the user
    - Gromacs mass fixes by using a custom atommass.dat file with extended atom names
    - Hidden unnecessary output logs and grey-colored necessary ones
    - Missing output checks
    Then return both output and error logs. """

    # Set the working directory as the path for GROMACS where to look for supplementary data files
    # Here we will make a copy of the atommass.dat file
    environ["GMXLIB"] = GLOBALS["working_directory"]

    # Run a fix for gromacs masses if not done before
    fix_gromacs_masses()

    # In case we have user input we must open a process to then pipe it in the gromacs process
    if user_input:
        # The -e option allows the interpretation of '\', which is critial for the make_ndx command
        # WARNING: Explicity split by whitespaces
        # WARNING: If not specified then breaklines are also removed, which is ciritcal for make_ndx
        user_input_process = Popen([ "echo", "-e", *user_input.split(' ') ], stdout=PIPE)

    # Get the time at the moment we start to run the command
    # WARNING: We must truncate this value, because the file mtime is truncated as well
    # Otherwise it may happen that gromacs runs in less than 1 seconds and the start time is higher
    start_time = time().__trunc__()

    # If error is to be shown the color it in grey
    # This is usually used to see progress logs
    if show_error_logs: print(GREY_HEADER)

    # Set the gromacs process
    process = run([ GROMACS_EXECUTABLE, *command.split(), '-quiet' ],
        stdin = user_input_process.stdout if user_input else None,
        stdout = PIPE, stderr = PIPE if not show_error_logs else None)

    # Get the gromacs process output
    output_logs = process.stdout.decode()
    # Get also error logs if necessary
    error_logs = process.stderr.decode() if not show_error_logs else None

    # End the grey coloring
    if show_error_logs: print(COLOR_END)

    # In case the expected output is set as 'auto' we must guess it from the command
    # Normally output comes after the '-o' option
    if expected_output_filepath == 'auto':
        command_splits = command.split()
        if '-o' not in command_splits: expected_output_filepath = None
        else:
            option_flag_index = command_splits.index('-o')
            expected_output_filepath = command_splits[option_flag_index + 1]

    # If an output file was expected then check it was created
    if expected_output_filepath:
        # Make sure output exists
        output_exists = exists(expected_output_filepath)
        # Make sure output have been generated by the gromacs command and it is not an old output
        output_is_old = False
        if output_exists:
            output_time = getmtime(expected_output_filepath)
            output_is_old = output_time < start_time
        # If output was not generated then we report the problem
        if not output_exists or output_is_old:
            # If we recognize the error and can provide any clue then this is the moment
            error_match = findall(GROMACS_MASSES_ERROR, error_logs)
            if error_match:
                warn(f'We are missing the masses for some atoms: {", ".join(error_match)}\n' + \
                    '  Are they dummy atoms?\n' + \
                    '  If so, please select them using the "dummy_selection" input field.\n' + \
                    '  Dummy atoms will be considered to have mass = 0.\n' + \
                    '  Are they Coarse Grain (CG) beads?\n' + \
                    '  If so, please select them using the "cg_selection" input field.\n' + \
                    '  Coarse Grain beads will be considered to have mass = 1.\n' + \
                    f'  If you want to set custom masses for these atoms then please edit the {GROMACS_MASSES_FILENAME} file in the project directory.')
            # If we don't know the error then simply output all the logs
            else:
                print(output_logs)
                print(error_logs)
            # Recreate the exact command
            final_command = f'{GROMACS_EXECUTABLE} {command}'
            if user_input: final_command += f' (with user input "{user_input}")'
            raise ToolError(f'Something went wrong with Gromacs while running "{GROMACS_EXECUTABLE} {command}"')

    # If all was good then show final logs but only if it was requested
    if show_output_logs: print(output_logs)

    # Return outputs
    return output_logs, error_logs


def get_first_frame_structure (input_structure_filename : str, input_trajectory_filename : str, output_frame_filename : str):
    """ Get the first frame from a trajectory as a structure. """
    # Run Gromacs
    run_gromacs(f'trjconv -s {input_structure_filename} -f {input_trajectory_filename} \
                -o {output_frame_filename} -dump 0', user_input = 'System')

# Set function supported formats
get_first_frame_structure.format_sets = [
    {
        'inputs': {
            'input_structure_filename': GROMACS_SUPPORTED_INPUT_TOPOLOGY_FORMATS,
            'input_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_frame_filename': GROMACS_SUPPORTED_STRUCTURE_FORMATS
        }
    },
    {
        'inputs': {
            'input_structure_filename': None,
            'input_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_frame_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        }
    },
    {
        'inputs': {
            'input_structure_filename': None,
            'input_trajectory_filename': {'pdb'}
        },
        'outputs': {
            'output_frame_filename': {'pdb', 'xtc', 'trr'}
        }
    },
    {
        'inputs': {
            'input_structure_filename': None,
            'input_trajectory_filename': {'gro'}
        },
        'outputs': {
            'output_frame_filename': {'gro', 'xtc', 'trr'}
        }
    }
]


def get_structure (input_structure_filename : str, input_trajectory_filename : str, output_structure_filename : str):
    """ Get the structure using the first frame getter function. """
    get_first_frame_structure(input_structure_filename, input_trajectory_filename, output_structure_filename)
get_structure.format_sets = [
    {
        'inputs': {
            'input_structure_filename': GROMACS_SUPPORTED_INPUT_TOPOLOGY_FORMATS,
            'input_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_structure_filename': GROMACS_SUPPORTED_STRUCTURE_FORMATS
        }
    }
]


def get_structure_alone (input_structure_filename : str, output_structure_filename : str):
    """ Convert the structure using the first frame getter function (no trajectory is required). """
    get_first_frame_structure(input_structure_filename, input_structure_filename, output_structure_filename)
get_structure_alone.format_sets = [
    {
        'inputs': {
            'input_structure_filename': GROMACS_SUPPORTED_STRUCTURE_FORMATS,
        },
        'outputs': {
            'output_structure_filename': GROMACS_SUPPORTED_STRUCTURE_FORMATS
        }
    }
]

def get_first_frame_trajectory (input_trajectory_filepath : str, output_frame_filepath : str):
    """ Get the first frame from a trajectory as a trajectory. """
    # Run Gromacs
    run_gromacs(f'trjconv -f {input_trajectory_filepath} -o {output_frame_filepath} -dump 0')

def merge_and_convert_trajectories (input_trajectory_filenames : list[str], output_trajectory_filename : str):
    """ Get gromacs supported trajectories merged and converted to a different format. """
    # Get trajectory formats
    sample_trajectory = input_trajectory_filenames[0]
    sample_trajectory_file = File(sample_trajectory)
    input_trajectories_format = sample_trajectory_file.format
    output_trajectory_file = File(output_trajectory_filename)
    output_trajectory_format = output_trajectory_file.format
    auxiliar_single_trajectory_filename = '.single_trajectory.' + input_trajectories_format
    # If we have multiple trajectories then join them
    if len(input_trajectory_filenames) > 1:
        single_trajectory_filename = auxiliar_single_trajectory_filename
        run_gromacs(f'trjcat -f {" ".join(input_trajectory_filenames)} \
                    -o {single_trajectory_filename}')
    else:
        single_trajectory_filename = sample_trajectory
    # In case input and output formats are different we must convert the trajectory
    if input_trajectories_format != output_trajectory_format:
        run_gromacs(f'trjconv -f {single_trajectory_filename} \
                    -o {output_trajectory_filename}')
    else:
        copyfile(single_trajectory_filename, output_trajectory_filename)
    # Remove residual files
    if exists(auxiliar_single_trajectory_filename):
        remove(auxiliar_single_trajectory_filename)

merge_and_convert_trajectories.format_sets = [
    {
        'inputs': {
            'input_trajectory_filenames': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        }
    },
    {
        'inputs': {
            'input_trajectory_filenames': {'pdb'}
        },
        'outputs': {
            'output_trajectory_filename': {'pdb', 'xtc', 'trr'}
        }
    },
    {
        'inputs': {
            'input_trajectory_filenames': {'gro'}
        },
        'outputs': {
            'output_trajectory_filename': {'gro', 'xtc', 'trr'}
        }
    }
]


def get_trajectory_subset (
    input_trajectory_filename : str,
    output_trajectory_filename : str,
    start : int = 0,
    end : int = None,
    step : int = 1,
    frames : list[int] = [],
    skip : list[int] = []
):
    """ Get specific frames from a trajectory. """
    # Set a list with frame indices from
    output_frames = frames if frames and len(frames) > 0 else [ frame for frame in range(start, end, step) if frame not in skip ]

    # Generate the ndx file to target the desired frames
    auxiliar_ndx_filename = '.frames.ndx'
    generate_frames_ndx(output_frames, auxiliar_ndx_filename)

    # Now run gromacs trjconv command in order to extract the desired frames
    run_gromacs(f'trjconv -f {input_trajectory_filename} -o {output_trajectory_filename} \
                -fr {auxiliar_ndx_filename}', user_input = 'System')

    # Cleanup the auxiliar ndx file
    remove(auxiliar_ndx_filename)


get_trajectory_subset.format_sets = [
    {
        'inputs': {
            'input_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_trajectory_filename': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        }
    }
]


def filter_structure (
    input_structure_file : 'File',
    output_structure_file : 'File',
    input_selection : 'Selection'
):
    """ Filter trajectory atoms. """
    # Generate a ndx file with the desired selection
    filter_selection_name = 'filter'
    filter_index_content = input_selection.to_ndx(selection_name=filter_selection_name)
    filter_index_filename = '.filter.ndx'
    with open(filter_index_filename, 'w') as file:
        file.write(filter_index_content)

    # Filter the structure
    run_gromacs(f'editconf -f {input_structure_file.path} -o {output_structure_file.path} \
                -n {filter_index_filename}', user_input = filter_selection_name)

    # Cleanup the index file
    remove(filter_index_filename)

filter_structure.format_sets = [
    {
        'inputs': {
            'input_structure_file': GROMACS_SUPPORTED_STRUCTURE_FORMATS,
        },
        'outputs': {
            'output_structure_file': GROMACS_SUPPORTED_STRUCTURE_FORMATS
        }
    }
]


def filter_trajectory (
    input_structure_file : 'File',
    input_trajectory_file : 'File',
    output_trajectory_file : 'File',
    input_selection : 'Selection'
):
    """ Filter trajectory atoms. """
    # Generate a ndx file with the desired selection
    filter_selection_name = 'filter'
    filter_index_content = input_selection.to_ndx(selection_name=filter_selection_name)
    filter_index_filename = '.filter.ndx'
    with open(filter_index_filename, 'w') as file:
        file.write(filter_index_content)

    # Filter the trajectory
    # Now run gromacs trjconv command in order to extract the desired frames
    run_gromacs(f'trjconv -s {input_structure_file.path} -f {input_trajectory_file.path} \
                -o {output_trajectory_file.path} -n {filter_index_filename}',
                user_input = filter_selection_name)

    # Cleanup the index file
    remove(filter_index_filename)

filter_trajectory.format_sets = [
    {
        'inputs': {
            'input_structure_file': GROMACS_SUPPORTED_INPUT_TOPOLOGY_FORMATS,
            'input_trajectory_file': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        },
        'outputs': {
            'output_trajectory_file': GROMACS_SUPPORTED_TRAJECTORY_FORMATS
        }
    }
]

# Set a regular expression to further mine data from gromacs logs
GROMACS_SYSTEM_ATOMS_REGEX = r'System\) has[ ]+([0-9]*) elements'


def mine_system_atoms_count (logs : str) -> int:
    """ Mine system atoms count from gromacs logs. """
    system_atoms_match = search(GROMACS_SYSTEM_ATOMS_REGEX, logs)
    if not system_atoms_match:
        print(logs)
        raise ValueError('Failed to mine Gromacs error logs')
    return int(system_atoms_match[1])


def get_tpr_atom_count (tpr_filepath : str) -> int:
    """ Count TPR atoms. """
    # Make sure the filepath is valid
    if not exists(tpr_filepath):
        raise ValueError('Trying to count atoms from a topology which does not exist')
    # Run Gromacs only to see the number of atoms in the TPR
    output_logs, error_logs = run_gromacs(f'convert-tpr -s {tpr_filepath}', user_input = "whatever")
    # Mine the number of atoms in the system from the logs
    atom_count = mine_system_atoms_count(error_logs)
    return atom_count


def read_and_parse_tpr (tpr_filepath : str) -> dict:
    """ Read and parse a tpr using the MDDB-specific tool from gromacs. """
    expected_output_filepath = 'siminfo.json'
    run_gromacs(f'dump -s {tpr_filepath} --json', expected_output_filepath = expected_output_filepath)
    parsed_tpr = load_json(expected_output_filepath)
    remove(expected_output_filepath)
    return parsed_tpr


def get_tpr_content (tpr_filepath : str) -> tuple[str, str]:
    """ Read a tpr file by converting it to ASCII. """
    # Read the tpr file making a 'dump'
    return run_gromacs(f'dump -s {tpr_filepath}')

# Regular expresion to mine atom charges
GROMACS_TPR_ATOM_CHARGES_REGEX = r"q=([0-9e+-. ]*),"


def get_tpr_charges (tpr_filepath : str) -> list[float]:
    """ Get tpr atom charges.
    This works for the new tpr format (tested in 122). """
    # Read the TPR
    tpr_content, tpr_error_logs = get_tpr_content(tpr_filepath)
    # Mine the atomic charges
    charges = []
    # Iterate tpr content lines
    for line in tpr_content.split('\n'):
        # Skip everything which is not atomic charges data
        if line[0:16] != '            atom': continue
        # Parse the line to get only charges
        match = search(GROMACS_TPR_ATOM_CHARGES_REGEX, line)
        if match: charges.append(float(match[1]))
    # If we successfully got atom charges then return them
    if len(charges) > 0: return charges
    # If there are no charges at the end then something went wrong
    print(tpr_error_logs)
    raise RuntimeError(f'Charges extraction from tpr file "{tpr_filepath}" has failed')

# Regular expresion to mine atom bonds
GROMACS_TPR_ATOM_BONDS_REGEX = r"^\s*([0-9]*) type=[0-9]* \((BONDS|CONSTR|CONNBONDS)\)\s*([0-9]*)\s*([0-9]*)$"
# Set a regular expression for SETTLE bonds, used for rigid waters
# ---- From the paper ------------------------------------------------------------------------------------
# The SETTLE can be applied to a four-point water model like TIP4P5 which has the fourth point with
# a certain charge and no mass if the force acting on the fourth point is distributed onto the other three
# points with masses in a reasonable manner.
# S. Miyamoto and P.A. Kollman, “SETTLE: An analytical version of the SHAKE and RATTLE algorithms for rigid
# water models,” J. Comp. Chem., 13 952–962 (1992)
# --------------------------------------------------------------------------------------------------------
# So it may happen that we encounter SETTLE with 4 atoms
# This is not yet supported, but at least we check if this is happening to raise an error when found
GROMACS_TPR_SETTLE_REGEX = r"^\s*([0-9]*) type=[0-9]* \(SETTLE\)\s*([0-9]*)\s*([0-9]*)\s*([0-9]*)\s*([0-9]*)$"

# Set the fields including vsites in the tpr dump tool
VIRTUAL_SITE_FIELDS = ['virtual_site_1', 'virtual_site_2', 'virtual_site_3', 'virtual_site_4', 'virtual_site_n']

def get_tpr_bonds (tpr_filepath : str) -> list[ tuple[int, int] ]:
    """ Get tpr atom bonds. """
    # Read and parse the TPR
    parsed_tpr = read_and_parse_tpr(tpr_filepath)
    topology = parsed_tpr['gromacs-topology']
    # Get the actual bonds
    tpr_bonds = topology['bond']['value']
    # Get virtual sites with bond-like annotations
    # These are not actual bonds, but some CG models such as Martini use them as such
    # If not consider, some beads may remain non-bonded to anything thus breaking our logic
    # DANI: I check for the field to exist just to support old versions of the tool
    for virtual_size_field in VIRTUAL_SITE_FIELDS:
        virtuals = topology.get(virtual_size_field, None)
        if not virtuals: continue
        # Add a bond between the first atom index and each of the rest of atom indices
        for virtual in virtuals['value']:
            main = virtual[0]
            for other in virtual[1:]:
                fake_bond = [main, other]
                tpr_bonds.append(fake_bond)
    return tpr_bonds


def filter_tpr (
    input_structure_file : 'File',
    output_structure_file : 'File',
    input_selection : 'Selection'
):
    """ Filter topology atoms.
    DANI: Note that a TPR file is not a structure but a topology
    DANI: However it is important that the argument is called 'structure' for the format finder"""
    # Generate a ndx file with the desired selection
    filter_selection_name = 'filter'
    filter_index_content = input_selection.to_ndx(selection_name=filter_selection_name)
    filter_index_filename = '.filter.ndx'
    with open(filter_index_filename, 'w') as file:
        file.write(filter_index_content)

    # Filter the tpr
    run_gromacs(f'convert-tpr -s {input_structure_file.path} -o {output_structure_file.path} \
                -n {filter_index_filename}', user_input = filter_selection_name)

    # Cleanup the index file
    remove(filter_index_filename)

filter_tpr.format_sets = [
    {
        'inputs': {
            'input_structure_file': {'tpr'},
        },
        'outputs': {
            'output_structure_file': {'tpr'}
        }
    }
]


def merge_xtc_files (current_file : str, new_file : str):
    """ Join xtc files.
    This is a minimal implementation of 'gmx trjcat' used in loops. """
    # If the current file does nt exist then set the new file as the current file
    if not exists(current_file):
        rename(new_file, current_file)
        return
    # Run trjcat
    run_gromacs(f'trjcat -f {new_file.path} {current_file} -o {current_file.path}')


def generate_frames_ndx (frames : list[int], filename : str):
    """ Generate a ndx file with a selection of frames. """
    # Add a header
    content = '[ frames ]\n'
    count = 0
    for frame in frames:
        # Add a breakline each 15 indices
        count += 1
        if count == 15:
            content += '\n'
            count = 0
        # Add a space between indices
        # Atom indices go from 0 to n-1
        # Add +1 to the index since gromacs counts from 1 to n
        content += str(frame + 1) + ' '
    content += '\n'
    # Write the file
    with open(filename, 'w') as file:
        file.write(content)

# DANI: No se usa, pero me costó un rato ponerla a punto así que la conservo
# Set a function to read and parse xpm files with a single matrix
# Inspired in https://gromacswrapper.readthedocs.io/en/latest/_modules/gromacs/fileformats/xpm.html#XPM
def parse_xpm (filename : str) -> list[ list[float] ]:
    with open(filename) as file:
        # First lines include metadata such as the title, description and legend
        # Read lines until we find the start of the array
        metadata = [file.readline()]
        while not metadata[-1].startswith("static char *gromacs_xpm[]"):
            metadata.append(file.readline())
        # The next line will contain the dimensions of the matrix
        # e.g. "7 7   14 1",
        dimensions = file.readline().replace('"','').replace(',','').split()
        x_dimension, y_dimension, entity_count, x_stride = [ int(i) for i in dimensions ]
        # Next lines contain every entity definition
        # Every entity has the following:
        # - A letter which is used to refer this entity later in the matrix
        # - A color in #XXXXXX format
        # - The actual value of the entity
        # e.g. "A  c #FFFFFF " /* "0" */,
        # e.g. "B  c #EBEBFF " /* "1" */,
        entities = {}
        for i in range(entity_count):
            line = file.readline()
            entity_id = line[1]
            entity_color = line[6:13]
            entity_value = line[18:].split('"')[1]
            entities[entity_id] = { 'value': entity_value, 'color': entity_color }
        # Next lines are the matrix axis values
        x_axis = []
        y_axis = []
        # Every line has a maximum of 80 labels
        x_lines = math.ceil(x_dimension / 80) # type: ignore
        for l in range(x_lines):
            line = file.readline()[12:-3].split()
            x_axis += [ int(v) for v in line ]
        y_lines = math.ceil(y_dimension / 80) # type: ignore
        for l in range(y_lines):
            line = file.readline()[12:-3].split()
            y_axis += [ int(v) for v in line ]
        # Next lines are the matrix rows
        matrix = []
        for l in range(y_dimension):
            line = file.readline()[1:1+x_dimension]
            row = [ letter for letter in line ]
            matrix.append(row)
        # Check the final matrix size is as expected
        if len(matrix) != y_dimension:
            raise ValueError('Different number of rows than expected')
        sample_row = matrix[-1]
        if len(sample_row) != x_dimension:
            raise ValueError('Different number of columns than expected')
        # Return the output
        return { 'entities': entities, 'x_axis': x_axis, 'y_axis': y_axis, 'matrix': matrix }


def pdb_filter (
    input_pdb_filepath : str,
    output_pdb_filepath : str,
    index_filepath : str,
    filter_group_name : str
):
    """ Filter atoms in a pdb file.
    This method conserves maximum resolution and chains.
    DEPRECATED: Gromacs assigns elements when missing and the guessing logic is limited
    The structure further may fix these elements but then we see a lot of warnings which are nonsense
    """
    # Filter the PDB
    run_gromacs(f'editconf -f {input_pdb_filepath} -o {output_pdb_filepath} \
                -n {index_filepath}', user_input = filter_group_name)


def xtc_filter(
    structure_filepath : str,
    input_trajectory_filepath : str,
    output_trajectory_filepath : str,
    index_filepath : str,
    filter_group_name : str
):
    """ Filter atoms in a xtc file.
    Note that here we do not hide the stderr.
    This is because it shows the progress.
    Instead we color the output grey. """
    # Filter the trajectory
    run_gromacs(f'trjconv -s {structure_filepath} -f {input_trajectory_filepath} \
        -o {output_trajectory_filepath} -n {index_filepath}', user_input = filter_group_name)


def tpr_filter(
    input_tpr_filepath : str,
    output_tpr_filepath : str,
    index_filepath : str,
    filter_group_name : str
):
    """ Filter atoms in both a pdb and a xtc file. """
    # Filter the topology
    run_gromacs(f'convert-tpr -s {input_tpr_filepath} -o {output_tpr_filepath} \
                -n {index_filepath}', user_input = filter_group_name)


def make_index (input_structure_file : 'File', output_index_file : 'File', mask : str) -> str:
    """ Create a .ndx file from a complex mask.
    e.g. no water and no ions -> !"Water"&!"Ion".
    This will return the group name to be further used. """
    # Make sure the
    #if output_index_file.exists: output_index_file.remove()
    # Run Gromacs
    run_gromacs(f'make_ndx -f {input_structure_file.path} -o {output_index_file.path}',
                user_input = f'{mask} \nq')
    # The group name is automatically assigned by gromacs
    # It equals the mask but removing any " symbols and with a few additional changes
    # WARNING: Not all mask symbols are supported here, beware of complex masks
    group_name = mask.replace('"','').replace('&','_&_').replace('|','_')
    # Check if the group was created
    content = read_ndx(output_index_file)
    created = group_name in content
    return group_name, created


def read_ndx (input_index_file : 'File') -> dict:
    """ Read a .ndx file """
    # Make sure the file exists
    if not input_index_file.exists:
        raise RuntimeError(f'Index file {input_index_file.path} does not exist')
    # Read the ndx file
    ndx_content = None
    with open(input_index_file.path, 'r') as file:
        ndx_content = file.readlines()
    # Parse its contents
    groups = {}
    current_group_name = None
    current_group_indices = None
    for line in ndx_content:
        # If it is the header of a group of indices
        if line[0] == '[':
            # Add current group to the final dict
            if current_group_name != None:
                groups[current_group_name] = current_group_indices
            # Set the name and the list of indices for the next group
            current_group_name = line[2:-3]
            current_group_indices = []
            continue
        # If it is a line of indices then parse it to actual numbers
        # Substract 1 since gromacs indices are 1-based while we want them 0-based
        current_group_indices += [ int(index) - 1 for index in line.split() ]
    # Add last group to the final dict
    groups[current_group_name] = current_group_indices
    # Finally return the parsed content
    return groups


ATOMS_LINE = r'\n# Atoms\s*([0-9]*)\n'
def get_gmx_atom_count (mysterious_file : 'File') -> int:
    """ Count atoms in a gromacs supported file. """
    output_logs, error_logs =  run_gromacs(f'check -f {mysterious_file.path}')
    search_results = search(ATOMS_LINE, error_logs)
    if not search_results: raise ValueError('Failed to mine atoms')
    return int(search_results[1])

def get_gmx_trajectory_atom_count (mysterious_file : 'File') -> int:
    """ Count atoms in a gromacs supported trajectory file. Check only the first frame. """
    # Generate a trajectory with inle the first sample
    first_frame_sample_filepath = get_auxiliar_filepath(f'.first_frame.{mysterious_file.extension}')
    first_frame_sample_file = File(first_frame_sample_filepath)
    get_first_frame_trajectory(mysterious_file.path, first_frame_sample_file.path)
    # Check this trajectory to get the atom count
    atom_count = get_gmx_atom_count(first_frame_sample_file)
    # Clean up the auxiliar files
    remove(first_frame_sample_file.path)
    return atom_count


# ---- XTC low-level utilities (Claude) ------------------------------------------------------------------
#
# XTC is the GROMACS compressed trajectory format.  Each frame is an XDR
# (big-endian) record with the following layout:
#
#   int32    magic       (always 1995)
#   int32    natoms
#   int32    step
#   float32  time
#   float32[9] box       (3×3 matrix, nm, row-major — diagonal = Lx, Ly, Lz)
#   int32    natoms      (repeated)
#   -- if natoms <= 9 the coordinates are not compressed: --
#   float32[3*natoms]    coordinates
#   -- otherwise: --
#   float32  precision
#   int32[3] minint
#   int32[3] maxint
#   int32    smallidx
#   int32    ncoord_bytes   (byte count of the compressed coordinate block)
#   bytes[ceil(ncoord_bytes/4)*4]  (3dfcoord-compressed integers, XDR-padded)
#
# Because ncoord_bytes is stored in the header we can skip the compressed
# block entirely and jump straight to the next frame.  This avoids the full
# 3dfcoord decompression and yields ~50× speed-up over mdtraj/pytraj when
# only box dimensions or a frame count are needed.
#
# Note: ncoord_bytes is frame-specific (depends on coordinate range) so
# frame sizes are not constant in general.
# --------------------------------------------------------------------------------------------------------

_XTC_MAGIC = 1995
# Byte offsets within a frame (after the 4-byte magic):
#   natoms(4) + step(4) + time(4) + box(36) = 48  → box starts at byte 12 of this block
_XTC_PRE_BOX    = 48    # bytes to read after magic: covers natoms/step/time/box
_XTC_BOX_OFFSET = 12    # offset of box within that 48-byte block
# Compressed block header before ncoord_bytes: precision(4) + minint(12) + maxint(12) + smallidx(4)
_XTC_COMPRESSED_HEADER = 32
# Systems with this many atoms or less store their coordinates without compression
_XTC_MAX_UNCOMPRESSED_ATOMS = 9

def _skip_xtc_coordinates (f) -> bool:
    """Move the file cursor from right after the box to the start of the next frame.
    Return False if the file ends before.

    Made by Claude.
    """
    raw = f.read(4)
    if len(raw) < 4: return False
    natoms = struct.unpack('>i', raw)[0]
    if natoms <= _XTC_MAX_UNCOMPRESSED_ATOMS:
        f.seek(3 * 4 * natoms, 1)
        return True
    f.seek(_XTC_COMPRESSED_HEADER, 1)
    raw = f.read(4)
    if len(raw) < 4: return False
    ncoord_bytes = struct.unpack('>i', raw)[0]
    f.seek(((ncoord_bytes + 3) // 4) * 4, 1)
    return True

def get_xtc_frame_count(xtc_path: str, verbose: bool = True) -> int:
    """Count the number of frames in an XTC file without loading coordinates.

    Scans the file by reading only the small per-frame header and skipping the
    compressed coordinate block via the stored byte-count field.
    ~3× faster than pytraj and requires no topology file.

    Made by Claude.
    """
    if verbose: print('-> Counting number of frames')
    count = 0
    magic_bytes = struct.pack('>i', _XTC_MAGIC)
    with open(xtc_path, 'rb') as f:
        while True:
            if f.read(4) != magic_bytes:
                break
            f.seek(_XTC_PRE_BOX, 1)
            if not _skip_xtc_coordinates(f):
                break
            count += 1
    if verbose: print(f' Frames: {count}')
    return count

# Set the workflow task to read frames
def count_xtc_frames (trajectory_file : 'File') -> int:
    return get_xtc_frame_count(xtc_path=trajectory_file.path)

# ---- Box shape classification (Claude) -----------------------------------------------------------------
#
# The same periodic box can be written with different sets of box vectors.
# e.g. AMBER writes the truncated octahedron with three 109.47° angles while
# GROMACS writes it with 70.53°, 109.47° and 70.53°, yet both are the same box.
# Thus comparing the box vectors against templates is not reliable.
#
# Instead we look at the periodic translations of the box: every integer
# combination of box vectors moves the system onto one of its periodic images.
# The three shortest translations which do not lie in the same line or plane
# are the same whatever the box vectors we were given, so their lengths and
# angles characterise the box shape.
# Angles are folded into [0°, 90°] since a translation and its opposite are
# equivalent (e.g. 60° and 120° both count as 60°).
#
# Expected shortest translations for every shape:
#   cubic        — 3 equal lengths, angles 90° 90° 90°
#   orthogonal   — any lengths, angles 90° 90° 90°
#   hexagonal    — 2 equal lengths at 60°, the third one perpendicular to both
#   dodecahedral — 3 equal lengths, angles 60° 60° 60° or 60° 60° 90°
#   octahedral   — 3 equal lengths, angles 70.53° 70.53° 70.53° (truncated octahedron)
#   triclinic    — anything else
# --------------------------------------------------------------------------------------------------------

# Integer combinations of box vectors used to enumerate periodic translations
# Coefficients up to 2 are enough for any reasonably shaped box (e.g. those written by MD engines)
# Tested also with boxes rewritten through random combinations of their vectors
_TRANSLATION_COEFFICIENTS = np.array(
    [(i, j, k) for i in range(-2, 3) for j in range(-2, 3) for k in range(-2, 3) if (i, j, k) != (0, 0, 0)],
    dtype=np.float64)
# Tolerances when comparing lengths (relative) and angles (degrees)
# They absorb float32 precision and the small fluctuations of isotropic pressure coupling
_BOX_SHAPE_LENGTH_TOLERANCE = 0.01
_BOX_SHAPE_ANGLE_TOLERANCE = 1.0
# Angle between the shortest translations of a truncated octahedron: acos(1/3)
_OCTAHEDRAL_ANGLE = float(np.degrees(np.arccos(1 / 3)))

# Number of frames classified at once, to limit memory usage (~50 MB per chunk)
_BOX_SHAPE_CHUNK_SIZE = 2000

def get_box_shapes (box_matrices : np.ndarray) -> list[str]:
    """Classify the shape of many periodic boxes given their box matrices (n_boxes, 3, 3), rows are box vectors.

    Returns a list with one of 'cubic', 'orthogonal', 'hexagonal', 'dodecahedral', 'octahedral'
    or 'triclinic' for every box. See the comment block above for the logic.
    All boxes are processed at once with numpy operations since classifying boxes one by one
    would be too slow for long trajectories with a dynamic box.

    Made by Claude.
    """
    box_matrices = np.asarray(box_matrices, dtype=np.float64).reshape(-1, 3, 3)
    shapes = []
    for start in range(0, len(box_matrices), _BOX_SHAPE_CHUNK_SIZE):
        shapes += _classify_box_shapes(box_matrices[start : start + _BOX_SHAPE_CHUNK_SIZE])
    return shapes

def get_box_shape (box_matrix : np.ndarray) -> str:
    """Classify the shape of a single periodic box given its box matrix (rows are box vectors).

    Made by Claude.
    """
    return get_box_shapes(box_matrix)[0]

def _classify_box_shapes (box_matrices : np.ndarray) -> list[str]:
    """Classify a chunk of box matrices (n_boxes, 3, 3). Used by get_box_shapes.

    Made by Claude.
    """
    n_boxes = len(box_matrices)
    rows = np.arange(n_boxes)
    # All periodic translations of every box and their lengths
    translations = np.einsum('tj,bjk->btk', _TRANSLATION_COEFFICIENTS, box_matrices)   # (n_boxes, n_translations, 3)
    lengths = np.linalg.norm(translations, axis=2)                                        # (n_boxes, n_translations)
    # Pick the shortest translation, then the shortest one not in its line,
    # then the shortest one not in the plane of the previous two
    # A small relative threshold makes float precision errors not count as out of line/plane
    first_index = np.argmin(lengths, axis=1)
    first = translations[rows, first_index]
    first_length = lengths[rows, first_index]
    out_of_line = np.linalg.norm(np.cross(first[:, np.newaxis, :], translations), axis=2) \
        > 1e-4 * first_length[:, np.newaxis] * lengths
    second = translations[rows, np.argmin(np.where(out_of_line, lengths, np.inf), axis=1)]
    normal = np.cross(first, second)
    out_of_plane = np.abs(np.einsum('btk,bk->bt', translations, normal)) \
        > 1e-4 * np.linalg.norm(normal, axis=1)[:, np.newaxis] * lengths
    third = translations[rows, np.argmin(np.where(out_of_plane, lengths, np.inf), axis=1)]
    shortest = np.stack([first, second, third], axis=1)                                  # (n_boxes, 3, 3)
    # These three translations must enclose the same volume as the box itself
    # Otherwise they skip some periodic images and they do not represent the box
    # This is not expected to happen, but in such case we can not tell the shape
    box_volumes = np.abs(np.linalg.det(box_matrices))
    represents_box = np.abs(np.abs(np.linalg.det(shortest)) - box_volumes) <= 1e-3 * box_volumes
    # Get lengths and folded angles
    # angles[:, k] is the angle between the two translations other than k
    shortest_lengths = np.linalg.norm(shortest, axis=2)                                  # (n_boxes, 3)
    def folded_angle (i, j):
        cosine = np.abs(np.sum(shortest[:, i] * shortest[:, j], axis=1)) \
            / (shortest_lengths[:, i] * shortest_lengths[:, j])
        return np.degrees(np.arccos(np.minimum(cosine, 1.0)))
    angles = np.stack([folded_angle(1, 2), folded_angle(0, 2), folded_angle(0, 1)], axis=1)
    def equal_lengths (i, j):
        a, b = shortest_lengths[:, i], shortest_lengths[:, j]
        return np.abs(a - b) <= _BOX_SHAPE_LENGTH_TOLERANCE * np.maximum(a, b)
    def angle_is (angle, target):
        return np.abs(angle - target) <= _BOX_SHAPE_ANGLE_TOLERANCE
    all_lengths_equal = equal_lengths(0, 1) & equal_lengths(1, 2) & equal_lengths(0, 2)
    # Check every shape
    all_right_angles = np.all(angle_is(angles, 90), axis=1)
    sorted_angles = np.sort(angles, axis=1)
    is_dodecahedral = all_lengths_equal & angle_is(sorted_angles[:, 0], 60) & angle_is(sorted_angles[:, 1], 60) \
        & (angle_is(sorted_angles[:, 2], 60) | angle_is(sorted_angles[:, 2], 90))
    is_octahedral = all_lengths_equal & np.all(angle_is(angles, _OCTAHEDRAL_ANGLE), axis=1)
    # Hexagonal: two equal translations at 60° and the third one perpendicular to both
    is_hexagonal = np.zeros(n_boxes, dtype=bool)
    for k in range(3):
        i, j = [index for index in range(3) if index != k]
        is_hexagonal |= equal_lengths(i, j) & angle_is(angles[:, k], 60) \
            & angle_is(angles[:, i], 90) & angle_is(angles[:, j], 90)
    # The first matching condition wins
    shapes = np.select(
        [~represents_box, all_right_angles & all_lengths_equal, all_right_angles,
         is_dodecahedral, is_octahedral, is_hexagonal],
        ['triclinic', 'cubic', 'orthogonal', 'dodecahedral', 'octahedral', 'hexagonal'],
        default='triclinic')
    return shapes.tolist()

def get_xtc_simulation_box(
    xtc_path: str, verbose: bool = True,
) -> tuple[
    Optional[tuple[tuple[float, float, float], ...] | str],
    Optional[tuple[float, float, float]],
    Optional[bool],
    Optional[bool],
    Optional[str],
]:
    """Read the simulation box from every frame of an XTC file.

    Skips compressed coordinates entirely (~50× faster than mdtraj/pytraj).

    Returns (box, box_size, is_constant, is_orthogonal, box_shape) where:
      box           — The three box vectors in Ångstroms, as a tuple of three
                      (x, y, z) tuples (rows of the box matrix).  They fully
                      define the periodic cell whatever its shape.
                      If the box is dynamic this is the flag 'dyn' instead.
      box_size      — (x, y, z) tuple in Ångstroms with the diagonal of the box
                      matrix.  For orthogonal boxes these are the box lengths,
                      but for triclinic boxes they are not the vector lengths.
                      For constant boxes this is the per-frame value; for
                      variable boxes this is the per-dimension maximum.
      is_constant   — True when the box vectors do not change significantly
                      across frames (relative std < 0.1 % in all elements).
      is_orthogonal — True when every off-diagonal element of the box matrix
                      is ~0 in every frame (rectangular box).
      box_shape     — 'cubic', 'orthogonal', 'hexagonal', 'dodecahedral',
                      'octahedral' or 'triclinic' (see get_box_shape).
                      If a dynamic box changes its shape along the trajectory
                      then all shapes are joined in order of appearance
                      (e.g. 'dodecahedral / triclinic').
    All five are None if no valid XTC frame is found or there is no box.

    Made by Claude.
    """
    # Box matrix of every frame, as 9 floats in nm (row-major)
    box_matrices: list[tuple[float, ...]] = []
    magic_bytes = struct.pack('>i', _XTC_MAGIC)

    with open(xtc_path, 'rb') as f:
        while True:
            if f.read(4) != magic_bytes:
                break
            data = f.read(_XTC_PRE_BOX)
            if len(data) < _XTC_PRE_BOX:
                break
            # Box is a 3×3 float32 matrix (nm); rows are the box vectors
            box_matrices.append(struct.unpack('>9f', data[_XTC_BOX_OFFSET : _XTC_BOX_OFFSET + 36]))
            if not _skip_xtc_coordinates(f):
                break

    if not box_matrices:
        return None, None, None, None, None

    matrices = np.array(box_matrices, dtype=np.float64).reshape(-1, 3, 3) * 10.0   # (n_frames, 3, 3) Å

    # Trajectories without a periodic box store an all-zero box matrix
    if not np.any(matrices):
        if verbose: print(' There is no simulation box')
        return None, None, None, None, None

    diagonals = np.diagonal(matrices, axis1=1, axis2=2)                            # (n_frames, 3) Å

    # Off-diagonal elements (triclinic tilt); 1e-3 Å is well below XTC coordinate precision
    off_diagonal_mask = ~np.eye(3, dtype=bool)
    is_orthogonal = bool(np.all(np.abs(matrices[:, off_diagonal_mask]) < 1e-3))

    # Every element varies less than 0.1 % of the mean length of its vector
    if matrices.shape[0] > 1:
        vector_lengths = np.linalg.norm(matrices, axis=2).mean(axis=0)   # (3,) Å
        variation = np.std(matrices, axis=0) / vector_lengths[:, np.newaxis]
        is_constant = bool(np.all(variation < 0.001))
    else:
        is_constant = True

    if is_constant:
        box = tuple(tuple(float(value) for value in vector) for vector in matrices[0])
        box_size = tuple(float(value) for value in diagonals[0])
        box_shape = get_box_shape(matrices[0])
    else:
        box = 'dyn'
        box_size = tuple(float(value) for value in diagonals.max(axis=0))
        # Pressure coupling may deform the box along the trajectory (e.g. semi-isotropic)
        # Classify every frame and keep the different shapes in order of appearance
        box_shape = ' / '.join(dict.fromkeys(get_box_shapes(matrices)))

    # Make a summary of the final box
    if verbose:
        if is_constant:
            print(f' Simulation box size is constant ({box_size[0]:.2f} × {box_size[1]:.2f} × {box_size[2]:.2f} Å)')
        else:
            print(f' Simulation box varies. Maximum size: ({box_size[0]:.2f} × {box_size[1]:.2f} × {box_size[2]:.2f} Å)')

        print(f' Simulation box shape: {box_shape}')

    return box, box_size, is_constant, is_orthogonal, box_shape