version: 2
build:
  os: ubuntu-24.04
  tools:
    # https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#build-tools-python
    python: "miniconda3-4.7"
  # jobs:
  #   build:
  #     html:
  #       - CONDA_PREFIX=$CONDA_ENVS_PATH/$CONDA_DEFAULT_ENV && python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html; env
  #       - env
# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/guides/conda.html
# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#conda
conda:
  environment: envs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 
sphinx:
  configuration: docs/source/conf.py
  builder: html