version: 2
build:
  os: ubuntu-24.04
  tools:
    # https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#build-tools-python
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - env
    pre_build:
      - env
      - conda init bash
      - conda activate $CONDA_DEFAULT_ENV

# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/guides/conda.html
# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#conda
conda:
  environment: envs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 
sphinx:
  configuration: docs/source/conf.py
  builder: html