version: 2
build:
  os: ubuntu-24.04
  tools:
    # https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#build-tools-python
    python: "mambaforge-4.10"
  jobs:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#update-conda-version
    # pre_create_environment:
    #   - conda update --yes --quiet --name=base --channel=defaults conda
    post_create_environment:
      # https://docs.readthedocs.com/platform/stable/reference/environment-variables.html#envvar-READTHEDOCS_VIRTUALENV_PATH
      - mamba init
      - source /home/docs/.bashrc
      - mamba activate $CONDA_DEFAULT_ENV
      - env

# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/guides/conda.html
# https://test.org.stsewd.dev/es/readthedocs-docs-build-commands/config-file/v2.html#conda
conda:
  environment: envs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 
sphinx:
  configuration: docs/source/conf.py
  builder: html