version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_create_environment:
      - conda update --yes --quiet --name=base --channel=defaults conda

conda:
  environment: envs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 
sphinx:
  configuration: docs/source/conf.py
  builder: html