name: mwf
channels:
  - bioconda
  - anaconda
  - ambermd
  - conda-forge
dependencies:
  - python=3.6
  - acpype
  - cmip
  - gromacs
  - pytraj
  - mdtraj
  - numpy 
  - prody
  - scikit-learn
  - fpocket