name: mwf_env
channels:
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.79
  - cmip
  - curves
  - fpocket
  - gromacs
  - mdanalysis
  - mdtraj
  - numpy
  - pip
  - pocl
  - python=3.7
  - scipy
  - sqlite=3.37.2
  - vmd
  - xmltodict
  - pyyaml
  - pip:
    - argparse
    - iminuit<2
    - pytraj
    - tmscoring
