from mddb_workflow.tools.get_screenshot import get_screenshot
from mddb_workflow.utils.auxiliar import InputError
from mddb_workflow.utils.mdt_spells import get_frame
from mddb_workflow.utils.type_hints import *


def get_project_screenshot(
    structure: 'Structure',
    structure_file: 'File',
    trajectory_file: 'File',
    snapshots: int,
    output_file: 'File',
    cg_selection: 'Selection',
    screenshot_frame: Optional[int] = None,
    parameters: Optional[dict] = None,
) -> dict:
    """Project screenshot is usually made with the reference frame, thus using the main structure.
    However the user may pass a custom frame.
    """
    reference_structure = structure
    # If a frame is passed then we must create an auxiliar structure with the pertinent coordinates
    if screenshot_frame is not None:
        # If the frame is negative then cit means we count starting by the end
        reference_frame = screenshot_frame if screenshot_frame >= 0 else snapshots + screenshot_frame
        if reference_frame < 0 or reference_frame >= snapshots:
            raise InputError(f'Frame {screenshot_frame} does not exist. The trajectory has {snapshots} frames.')
        # Get the specific frame coordinates
        frame = get_frame(structure_file, trajectory_file, reference_frame)
        coordinates = frame.xyz[0] * 10  # We multiply by to restor Ångstroms
        # WARNING: a PDB generated by MDtraj may have problems thus leading to artifacts in the screenshot
        # WARNING: to avoid this we add the coordinates to the structure
        # coordinates.save(AUXILIAR_PDB_FILENAME)
        # Copy the structure to further mutate its coordinates without affecting the original
        reference_structure = structure.copy()
        reference_structure.set_new_coordinates(coordinates)
    return get_screenshot(reference_structure, output_file, cg_selection, parameters)
